### ISSUE TITLE
private dockerhub registry

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre-binderhub#1]
Currently we have networking issues with computecanada. The pulling/building of the docker images takes forever.
To address this, we can create our own docker registry (to address our networking issues)

I know that computecanada is working on that so we should be in touch with them.

**Comment by ltetrel** [comment]
If we want to make it work within a private network with SSL encryption : 
https://hackernoon.com/create-a-private-local-docker-registry-5c79ce912620

**Comment by ltetrel** [comment]
Just posted a question on the binderhub discourse, since the local registry is not working. 
https://discourse.jupyter.org/t/custom-local-docker-regitry/2278

If it is not possible to do this, I will create a subdomain for the registry (which will be accessible from the outside), something like : binder.conp.cloud.registry

**Comment by lunebellec** [comment]
FYI https://hackernoon.com/create-a-private-local-docker-registry-5c79ce912620

**Comment by ltetrel** [comment]
created a local docker registry accessible through https on the local network

**Comment by lunebellec** [comment]
Is the solution satisfactory? Have you had a chance to test it?

**Comment by ltetrel** [comment]
I want to test it on our test server (I will not take the risk to test it on the main server, because we need it 100% usable for main's workshop). @mathieuboudreau has still lot of issues when creating a test server, I am working on it. I resolved few bugs but they are others.. When this will be done I will test the registry. For now I just tested it "locally" (pushing an pulling from a node, "outside" of binderhub)

**Comment by ltetrel** [comment]
Ok the server is working, I setup a registry on 443 port (https) to let binderhub request without troubles (if using a port, [this fails](https://github.com/jupyterhub/binderhub/blob/9fb6d3f97d68bd807d3996d54a67029977f9bba5/binderhub/builder.py#L274)  because of the `:` to specify the port).
The issue is that binderhub is complaining about self-signed certificate (which I already allowed on the server in `/etc/docker/certs.d`), but because they are using a [http request](https://github.com/jupyterhub/binderhub/blob/9fb6d3f97d68bd807d3996d54a67029977f9bba5/binderhub/registry.py#L212-L214), we would need to add an insecure option `validate_cert=False` which I don't think binderhub team would allow...

**Comment by ltetrel** [comment]
So we don't have choice to use a domain name and the public internet...

**Comment by ltetrel** [comment]
Posted another issue : https://github.com/jupyterhub/binderhub/issues/992

**Comment by ltetrel** [comment]
I will try to use a pod preset https://kubernetes.io/docs/tasks/inject-data-application/podpreset/ to mount the self-signed certificate on the hub.

**Comment by ltetrel** [comment]
To use a pod preset : https://stackoverflow.com/questions/50352621/where-is-kube-apiserver-located

**Comment by ltetrel** [comment]
Working with binder-registry.conp.cloud :)
Has some issues regarding docker auth on kubernetes. Resolved by followint [this](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry) :) 
Abandoned the idea to do a "true" local registry running just on our local network. Will come back to it later when we will want to do some optimization.
