### ISSUE TITLE
Create test servers

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre-binderhub#2]
We need a test server for the user (conp7 or conp8 ?). This way they could test their work before pushing to neurolibre.

**Comment by mathieuboudreau** [comment]
Use subdomains instead

**Comment by lunebellec** [comment]
any update on this?

**Comment by mathieuboudreau** [comment]
No, I had booked off the entire day tomorrow to start looking at this. @ltetrel could you upload any relevant files you used to set up the current server to the NeuroLibre infrastructure GDrive folder we created at the last meeting?

**Comment by ltetrel** [comment]
ok, regarding the different steps, maybe we could zoom together so I can create a clean document with your feedback.

**Comment by mathieuboudreau** [comment]
@ltetrel now that I've got one setup (link on slack), it works on https, and we have instructions on how to set it up, do you think this issue can be closed? Or is there anything else left on a to-do list that you'd like to be done beforehand? I guess what I did was a development server, so maybe we could remove ccbinder and rebuild a new one as a test server for users?

**Comment by ltetrel** [comment]
1. We first have to make sure we understood the issue with the https self-signed certificate.. We have this issue whenever we upgrade the server to the newest version of binderhub (even if we match the same binder version as the main server).
2. After that, they are few additional steps to complete the installation (.bashrc configuration, data caching mechanism, docker registry).
