### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre-binderhub#25]
To be citable we will need a DOI.
We could use zenodo for that.

**Comment by ltetrel** [comment]
Example from jupyter project :
https://github.com/jupyter/jupyter/issues/190

**Comment by mathieuboudreau** [comment]
Do we want NeuroLibre to be citable, or the NeuroLibre "project"/submissions to be citable?

**Comment by ltetrel** [comment]
Do we want the infrastructure to be citeable neurolibre/neurolibre-binderhub , or the platform itself neurolibre/submit? hahha

**Comment by ltetrel** [comment]
Actually I think the best option would be to make the github organisation citeable itself (both submission and infrastructure). Not sure if this is possible

**Comment by ltetrel** [comment]
doublon from https://github.com/neurolibre/neurolibre.com/issues/11
