### ISSUE TITLE
Feasability of creating our own cloud

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre-binderhub#26]
The idea is to create our own infrastructure using [openstack](https://www.openstack.org/).
openstack is an infrastructure-as-a-service software that we are using on compute canada to spawn a neurolibre instance.
This would give us the development flexibility (like load balancing) and independence we want.

**Comment by ltetrel** [comment]
I am using a machine accessible from outside with : 
* 4 (+4 hyperthreaded) cores Intel(R) Core(TM) i7-2600 CPU
* 8GB of RAM
* 1TB of storage

**Comment by ltetrel** [comment]
Following this tutorial for a minimal openstack configuration:
https://docs.openstack.org/devstack/latest/
Which uses this repo:
https://opendev.org/openstack/devstack

There is also microstack, not sure to understand what is the difference ?
https://ubuntu.com/openstack/install#workstation-deployment

**Comment by ltetrel** [comment]
Here they explain how we could add images to openstack :
https://computingforgeeks.com/adding-images-openstack-glance/

For example ubuntu:
https://cloud-images.ubuntu.com/

**Comment by ltetrel** [comment]
When running `openstack` cmd, remember to source the openrc file, if you don't :
```
Missing value auth-url required for auth plugin password
```

**Comment by ltetrel** [comment]
Issues when trying to access an instance from the outside.
Copied the netwrok infrastructure as Arbutus. All instances are in a private network. Outside world is accesible through a router.
Maybe this thread ? https://ask.openstack.org/en/question/44266/connect-vm-in-devstack-to-external-network/
Or this one : http://linuxpitstop.com/setup-openstack-instances-virtual-machines-with-external-connectivity-using-horizon-dashboard/

**Comment by ltetrel** [comment]
Because the machine was rebooted, openstack not worked anymore. I had to reinstall it but issues with mysql that prevent to reinstall openstack with `devstack` properly..
https://stackoverflow.com/questions/26583885/openstack-devstack-virtual-machine-installation-error

This one may work : https://askubuntu.com/questions/766038/error-installing-mysql-on-ubuntu-16-04

**Comment by ltetrel** [comment]
So after installing `devstack`, the proper way is ton uninstall it using `clean.sh` and `unstack.sh`.
Unfortunately, sometime they are `mysql` artifacts that stay on the machine and blocks any future installation. The only way is to reformat the disk, I am now using `microstack`which seems to be the best and cleaniest way to install openstack (official openstack trainings use it) : https://ubuntu.com/openstack/install#workstation-deployment

**Comment by ltetrel** [comment]
Also `devstack` is not meant to be rebooted vs `microstack` :
https://ask.openstack.org/en/question/123464/best-option-for-working-with-devstack/
Complete answer here : https://www.youtube.com/watch?v=0-iAHQQ1jPQ&feature=youtu.be&t=807

**Comment by ltetrel** [comment]
Huge trouble to use the `openstack-cli` even if I sourced the `admin-openrc.sh`...
`The request you have made requires authentication. (HTTP 401) (Request-ID: req-3fb4eb93-c4bf-40d2-b624-5272d1cd36a8)`
What is super weird is that I can connect to the dashboard with the same pass and user...

**Comment by agahkarakuzu** [comment]
What makes the problem huge? Have you tried the verified answer here https://ask.openstack.org/en/question/67398/error-openstack-the-request-you-have-made-requires-authentication-http-401/ ?

**Comment by ltetrel** [comment]
of course I tried that... it is not huge, it is just super annoying when I want to debug stuff

**Comment by ltetrel** [comment]
submitted a report to their team, in the mean time I will continue the configuration via the dashboard

**Comment by ltetrel** [comment]
I got an answer, I had to change the `/var/snap/microstack/common/etc/microstack.rc`. This one get sourced automatically by `microstack`, so on the controller we don't use the `admin-openrc.sh`.

**Comment by ltetrel** [comment]
Creating an image with the dashboard return an error:
`413 Request Entity Too Large`
Hopefully, with the `openstack-cli` it is working

**Comment by ltetrel** [comment]
Good ressource to setup an external network :
https://docs.openstack.org/mitaka/install-guide-ubuntu/launch-instance-networks-provider.html

https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/10/html/networking_guide/sec-connect-instance

**Comment by ltetrel** [comment]
We need to create a bridge from our provider networks (that gives us the external floating ips) to our server. This thread should be a good point to start :
https://stackoverflow.com/questions/49232524/openstack-setting-up-bridge

[Here](https://opendev.org/x/microstack/src/branch/master/tools/init/init/questions/__init__.py#L561-L564) we can correctly configure the name for the `physical provider network`. This name can be configured by the `neutron` module of openstack :
https://opendev.org/x/microstack/src/branch/master/snap-overlay/etc/neutron/plugins/ml2/openvswitch_agent.ini

**Comment by ltetrel** [comment]
When trying to create locally a binderhub instance, I just saw that volume creation is disabled.. Even if I see some command related to `cinder` (which is the API that openstack uses to manage storage).
Just posted a question on their gitpage :https://bugs.launchpad.net/microstack/+bug/1863667
